version: 2.1
jobs:
  notify-telegram:
    steps:
    - telegram/notify:
          message: Custom notification message.
  
  
orbs:
  telegram: woltsu/telegram@0.0.9
  # "cypress-io/cypress@1" installs the latest published
  # version "1.x.y" of the orb. We recommend you then use
  # the strict explicit version "cypress-io/cypress@1.x.y"
  # to lock the version and prevent unexpected CI changes
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      
      - cypress/run # "run" job comes from "cypress" orb
      - notify-telegram:
          requires:
           - cypress/run 