version: 2.1

orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          context: rpguia
          record: true
          store_artifacts: true
          post-steps:
             - run:
                  name: Build Success
                  when: on_success
                  command: curl "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage?disable_web_page_preview=true&chat_id=$TELEGRAM_CHAT_ID&parse_mode=HTML&disable_notification=false&text=<a href='$CIRCLE_BUILD_URL'>Build</a> ok ✅"
             - run:
                  name: Build failed
                  when: on_fail
                  command:  convert -fuzz 1% -delay 4x1 cypress/screenshots/**/*.png -coalesce fails.gif
             - store_artifacts:
                  path: fails.gif
                  destination: fails.gif
             - run:
                  name: Build failed
                  when: on_fail
                  command: curl "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendAnimation?disable_web_page_preview=false&chat_id=$TELEGRAM_CHAT_ID&parse_mode=HTML&disable_notification=false&animation=https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BUILD_NUM/artifacts/0/fails.gif&width=1280&height=720&caption=<a href='$CIRCLE_BUILD_URL'>Build</a> failed ❌ <a href='https://dashboard.cypress.io/projects/hx6dr1/runs'>dashboard</a>" 
                  
  
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - cypress/run:
          record: true
          store_artifacts: true
          post-steps:
             - run:
                  name: Build Success
                  when: on_success
                  command:   curl "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage?disable_web_page_preview=true&chat_id=$TELEGRAM_CHAT_ID&parse_mode=HTML&disable_notification=false&text=<a href='$CIRCLE_BUILD_URL'>Build</a> ok ✅"
             - run:
                  name: Build failed
                  when: on_fail
                  command:  convert -fuzz 1% -delay 4x1 cypress/screenshots/**/*.png -coalesce fails.gif
             - store_artifacts:
                  path: fails.gif
                  destination: fails.gif
             - run:
                  name: Build failed
                  when: on_fail
                  command: curl "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendAnimation?disable_web_page_preview=false&chat_id=$TELEGRAM_CHAT_ID&parse_mode=HTML&disable_notification=false&animation=https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BUILD_NUM/artifacts/0/fails.gif&width=1280&height=720&caption=<a href='$CIRCLE_BUILD_URL'>Build</a> failed ❌ <a href='https://dashboard.cypress.io/projects/hx6dr1/runs'>dashboard</a>"
                  