version: 2.1

orbs:
  telegram: woltsu/telegram@0.0.9
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          post-steps:
             - run:
                  name: Build Success
                  when: on_success
                  command: 
                    - telegram/notify:
                        message:  build succeeded.
             - run:
                  name: Build failed
                  when: on_fail
                  command: 
                    - telegram/notify:
                        message:  build failed.