version: 2.1

orbs:
  telegram: woltsu/telegram@0.0.9
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          post-steps:
             - when:
                condition: always
                steps:
                    - telegram/notify:
                        message: notified after.
             - unless:
                condition: always
                steps:
                    - telegram/notify:
                        message: notified after.

