version: 2.1

orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          post-steps:
             - run:
                  name: Build Success
                  when: on_success
                  command:   curl "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage?chat_id=$TELEGRAM_CHAT_ID&parse_mode=HTML&disable_notification=false&text=<b>Build ok</b>✅\n <a href='$CIRCLE_BUILD_URL'>build</a>"
             - run:
                  name: Build failed
                  when: on_fail
                  command:   curl "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage?chat_id=$TELEGRAM_CHAT_ID&parse_mode=HTML&disable_notification=false&text=<b>Build failed</b>❌\n <a href='$CIRCLE_BUILD_URL'>build</a>"