version: 2.1

orbs:
  telegram: woltsu/telegram@0.0.9
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          post-steps:
             - when:
                condition: on_fail
                steps:
                  - run:
                      command: echo 'when condition on_fail works'
             - run:
                  name: Build Success
                  when: on_success
                  shell: /bin/bash
                  command: echo 'build suc'
             - run:
                  name: Build failed
                  when: on_fail
                  command: echo 'build failed'